name: Continuos Integration with GitHub
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - users: actions/checkout@v3
      - name: set up JDK 11
        users: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: clean project
        run: chmod +x ./gradlew && .gradlew clean
      - name: run all tests
        run: .gradlew testClasses
      - name: create .jar and install
        run: ./gradlew bootJar